const fs = require("fs");
const path = require("path");

const {
  generateSpeech
} = require("../services/ttsService");

// ============================================================
// GENERATE SPEECH
// POST /api/tts/speech
// ============================================================

async function generateSpeechController(
  req,
  res
) {
  try {
    const { text } = req.body;

    if (
      !text ||
      typeof text !== "string"
    ) {
      return res.status(400).json({
        success: false,
        error:
          "Text is required"
      });
    }

    const trimmedText =
      text.trim();

    if (!trimmedText) {
      return res.status(400).json({
        success: false,
        error:
          "Text cannot be empty"
      });
    }

    const result =
      await generateSpeech(
        trimmedText
      );

    return res.status(200).json({
      success: true,
      audio: result
    });

  } catch (error) {
    console.error(
      "TTS error:",
      error
    );

    return res.status(500).json({
      success: false,
      error:
        "Failed to generate speech"
    });
  }
}

// ============================================================
// STREAM TTS AUDIO
// GET /api/tts/audio/:fileName
// ============================================================

function getAudioController(
  req,
  res
) {
  try {
    const {
      fileName
    } = req.params;

    // --------------------------------------------------------
    // Validate filename
    // Only allow filenames generated by our TTS service.
    // --------------------------------------------------------

    if (
      !fileName ||
      !/^tts-\d+\.wav$/i.test(
        fileName
      )
    ) {
      return res.status(400).json({
        success: false,
        error:
          "Invalid audio filename"
      });
    }

    const outputDir =
      path.resolve(
        process.cwd(),
        "outputs",
        "tts"
      );

    const filePath =
      path.join(
        outputDir,
        fileName
      );

    // --------------------------------------------------------
    // Extra protection against path traversal
    // --------------------------------------------------------

    const resolvedFilePath =
      path.resolve(filePath);

    if (
      !resolvedFilePath.startsWith(
        outputDir + path.sep
      )
    ) {
      return res.status(400).json({
        success: false,
        error:
          "Invalid audio path"
      });
    }

    // --------------------------------------------------------
    // Check file exists
    // --------------------------------------------------------

    if (
      !fs.existsSync(
        resolvedFilePath
      )
    ) {
      return res.status(404).json({
        success: false,
        error:
          "Audio file not found"
      });
    }

    const stats =
      fs.statSync(
        resolvedFilePath
      );

    if (
      !stats.isFile() ||
      stats.size === 0
    ) {
      return res.status(404).json({
        success: false,
        error:
          "Audio file is unavailable"
      });
    }

    // --------------------------------------------------------
    // Audio headers
    // --------------------------------------------------------

    res.setHeader(
      "Content-Type",
      "audio/wav"
    );

    res.setHeader(
      "Content-Length",
      String(stats.size)
    );

    res.setHeader(
      "Content-Disposition",
      `inline; filename="${fileName}"`
    );

    res.setHeader(
      "Accept-Ranges",
      "bytes"
    );

    // --------------------------------------------------------
    // Send audio
    // --------------------------------------------------------

    return res.sendFile(
      resolvedFilePath
    );

  } catch (error) {
    console.error(
      "TTS audio streaming error:",
      error
    );

    return res.status(500).json({
      success: false,
      error:
        "Failed to load audio"
    });
  }
}

module.exports = {
  generateSpeechController,
  getAudioController
};